/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PortionManager.java
 *
 * Created on 10/11/2011, 16:23:46
 */
package br.com.geomapa.ui.panels;

import br.com.geomapa.geodesic.Polygonal;
import br.com.geomapa.main.DataManagement;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author paulocanedo
 */
public class PortionManagerPanel extends javax.swing.JPanel {

    private PortionDataPanel portionDataPanel = new PortionDataPanel();

    /** Creates new form PortionManager */
    public PortionManagerPanel() {
        initComponents();

        portionDataPanel.setVisible(false);
        centerPanel.add(portionDataPanel);
        portionsList.setModel(DataManagement.getMainPolygonal().getListModel());
        portionsList.getSelectionModel().addListSelectionListener(new PortionListListener());
    }

    private class PortionListListener implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent lse) {
            Polygonal selected = (Polygonal) portionsList.getSelectedValue();

            if (selected == null) {
                portionDataPanel.setVisible(false);
            } else {
                portionDataPanel.setVisible(true);
                portionDataPanel.setPolygonal(selected);
                portionDataPanel.refresh();
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        portionsList = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());
        add(centerPanel, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(220, 132));

        portionsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(portionsList);

        jPanel2.add(jScrollPane1);

        add(jPanel2, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList portionsList;
    // End of variables declaration//GEN-END:variables
}
