/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegistrationPanel.java
 *
 * Created on 30/06/2011, 14:49:17
 */
package br.com.geomapa.ui.panels;

import br.com.geomapa.ui.panels.options.OptionsPanel;
import br.com.geomapa.util.SecurityUtils;
import java.io.IOException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author paulocanedo
 */
public final class RegistrationPanel extends javax.swing.JPanel {

    private final static long license = OptionsPanel.licenseNumber();
    private final static int daysRemanning = SecurityUtils.gmIsKeyValid() ? 1 : SecurityUtils.gmTrialRemainning(license);

    /** Creates new form RegistrationPanel */
    public RegistrationPanel() {
        initComponents();

        requestCodeField.setText("" + license);
        daysRemanningField.setText(String.format("Restam %d dias", daysRemanning));
        trialButton.setEnabled(canOpen());
        jPanel1.setVisible(false);
    }

    public static boolean canOpen() {
        return daysRemanning > 0;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        passField = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        requestCodeField = new javax.swing.JTextField();
        keyField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        trialButton = new javax.swing.JButton();
        daysRemanningField = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Usuário:");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel1.add(jLabel2, new java.awt.GridBagConstraints());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Senha:");
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jLabel3, gridBagConstraints);

        userField.setColumns(30);
        jPanel1.add(userField, new java.awt.GridBagConstraints());

        jButton1.setText("Registrar-se online");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jButton1, gridBagConstraints);

        passField.setColumns(30);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(passField, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, 36));
        jLabel1.setText("pcGeoCad");
        jPanel2.add(jLabel1);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Código de requisição:");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel3.add(jLabel4, new java.awt.GridBagConstraints());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Chave de ativação:");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jLabel5, gridBagConstraints);

        requestCodeField.setColumns(30);
        requestCodeField.setEditable(false);
        jPanel3.add(requestCodeField, new java.awt.GridBagConstraints());

        keyField.setColumns(30);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel3.add(keyField, gridBagConstraints);

        jButton2.setText("Registrar-se");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel3.add(jButton2, gridBagConstraints);

        trialButton.setText("Usar período de teste");
        trialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trialButtonActionPerformed(evt);
            }
        });
        jPanel4.add(trialButton);

        daysRemanningField.setText("Restam 30 dias");
        jPanel4.add(daysRemanningField);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jPanel4, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String keyfield = keyField.getText();
        if (SecurityUtils.gmIsKeyValid(license, keyfield)) {
            try {
                SecurityUtils.gmWriteKey(keyfield);
                _dispose();
            } catch (IOException ex) {
                //TODO nao foi possivel gravar a chave de licenca
            }
        } else {
            JOptionPane.showMessageDialog(null, "Chave inválida");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void trialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trialButtonActionPerformed
        _dispose();
    }//GEN-LAST:event_trialButtonActionPerformed

    private void _dispose() {
        JDialog.getWindows()[0].dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daysRemanningField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField keyField;
    private javax.swing.JPasswordField passField;
    private javax.swing.JTextField requestCodeField;
    private javax.swing.JButton trialButton;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
