/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RinexFormPanel.java
 *
 * Created on 09/05/2011, 14:42:45
 */
package br.com.geomapa.ui.panels;

import br.com.geomapa.importer.rinex.RinexFile;
import br.com.geomapa.importer.rinex.RinexHeader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author paulocanedo
 */
public class RinexFormPanel extends javax.swing.JPanel {

    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy kk:mm:ss");

    /** Creates new form RinexFormPanel */
    public RinexFormPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        nomeField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inicioObsField = new javax.swing.JTextField();
        fimObsField = new javax.swing.JTextField();
        coordAproxField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        duracaoRastreioField = new javax.swing.JTextField();

        jPanel1.setLayout(new java.awt.GridBagLayout());

        nomeField.setColumns(30);
        nomeField.setEditable(false);
        nomeField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(nomeField, gridBagConstraints);

        jLabel1.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel4.setText("Fim do rastreamento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel2.setText("Inicio do rastreamento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel6.setText("Coordenada aproximada (WGS 84)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel6, gridBagConstraints);

        inicioObsField.setColumns(30);
        inicioObsField.setEditable(false);
        inicioObsField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(inicioObsField, gridBagConstraints);

        fimObsField.setColumns(30);
        fimObsField.setEditable(false);
        fimObsField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(fimObsField, gridBagConstraints);

        coordAproxField.setColumns(30);
        coordAproxField.setEditable(false);
        coordAproxField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(coordAproxField, gridBagConstraints);

        jLabel3.setText("Duração do rastreio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);

        duracaoRastreioField.setColumns(30);
        duracaoRastreioField.setEditable(false);
        duracaoRastreioField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel1.add(duracaoRastreioField, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField coordAproxField;
    private javax.swing.JTextField duracaoRastreioField;
    private javax.swing.JTextField fimObsField;
    private javax.swing.JTextField inicioObsField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeField;
    // End of variables declaration//GEN-END:variables

    public void setRinexFile(RinexFile rinexFile) {
        try {
            RinexHeader header = rinexFile.getHeader();

            nomeField.setText(header.getMarkerName());
            inicioObsField.setText(sdf.format(header.getFirstObs()));

            Date lastObs = header.getLastObs();
            if (lastObs != null) {
                fimObsField.setText(sdf.format(lastObs));
            }
            duracaoRastreioField.setText(header.getDurationTimeAsString());
            coordAproxField.setText(header.getCoord());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RinexFormPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(RinexFormPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
