/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewRTPanel.java
 *
 * Created on 16/05/2011, 15:07:40
 */
package br.com.geomapa.ui.panels.options;

/**
 *
 * @author paulocanedo
 */
public class NewRTPanel extends javax.swing.JPanel {

    public static final NewRTPanel INSTANCE = new NewRTPanel();

    private NewRTPanel() {
        initComponents();
    }

    public ResponsavelTecnico getRT() {
        String nome, incra, crea, profissao;

        nome = nomeCompletoField.getText();
        incra = codigoIncraField.getText();
        crea = codigoCreaField.getText();
        profissao = profissaoField.getText();

        return new ResponsavelTecnico(nome, incra, crea, profissao);
    }

    public void clearAll() {
        nomeCompletoField.setText("");
        codigoIncraField.setText("");
        codigoCreaField.setText("");
        profissaoField.setText("");
    }
    
    public void setResponsavelTecnico(ResponsavelTecnico rt) {
        nomeCompletoField.setText(rt.getNome());
        codigoIncraField.setText(rt.getCodigoIncra());
        codigoCreaField.setText(rt.getCodigoCrea());
        profissaoField.setText(rt.getProfissao());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeCompletoField = new javax.swing.JTextField();
        codigoIncraField = new javax.swing.JTextField();
        codigoCreaField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        profissaoField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nome Completo");
        add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setText("Código no INCRA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("Código no CREA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(jLabel3, gridBagConstraints);

        nomeCompletoField.setColumns(20);
        add(nomeCompletoField, new java.awt.GridBagConstraints());

        codigoIncraField.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(codigoIncraField, gridBagConstraints);

        codigoCreaField.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(codigoCreaField, gridBagConstraints);

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel4.setText("Não utilize o caractere vírgula ,");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jLabel4, gridBagConstraints);

        jLabel5.setText("Profissão");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(jLabel5, gridBagConstraints);

        profissaoField.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        add(profissaoField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoCreaField;
    private javax.swing.JTextField codigoIncraField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nomeCompletoField;
    private javax.swing.JTextField profissaoField;
    // End of variables declaration//GEN-END:variables
}
