/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RBMCPanel.java
 *
 * Created on 01/07/2011, 14:08:10
 */
package br.com.geomapa.ui.panels.options;

import br.com.geomapa.util.MiscUtils;
import br.com.geomapa.geodesic.coordinate.GeographicCoordinate;
import br.com.geomapa.geodesic.coordinate.UTMCoordinate;
import br.com.geomapa.geodesic.rbmc.BaseRBMC;
import br.com.geomapa.geodesic.rbmc.UtilRBMC;
import br.com.geomapa.main.Main;
import br.com.geomapa.util.autoupdate.PC9Downloader;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author paulocanedo
 */
public class RBMCPanel extends javax.swing.JPanel {

    /** Creates new form RBMCPanel */
    public RBMCPanel() {
        initComponents();

        try {
            List<BaseRBMC> list = UtilRBMC.listAllRbmc();

            basesRbmcList.setModel(new DefaultComboBoxModel(list.toArray(new BaseRBMC[0])));
            basesRbmcList.getSelectionModel().addListSelectionListener(new RbmcListListener());
        } catch (IOException ex) {
            Logger.getLogger(RBMCPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(Main.getInstance(), "Falha ao carregar os arquivos de base RBMC.");
        }
    }

    private class RbmcListListener implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
            BaseRBMC selectedValue = (BaseRBMC) basesRbmcList.getSelectedValue();

            fillFields(selectedValue);

            descritivoButton.setEnabled(selectedValue != null);
        }
    }

    private void fillFields(BaseRBMC selectedValue) {
        if (selectedValue == null) {
            latitudeField.setText("");
            longitudeField.setText("");
            altElipField.setText("");
            coordEsteField.setText("");
            coordNorteField.setText("");
            meridianoCentralField.setText("");
            cidadeUfField.setText("");
            return;
        }

        GeographicCoordinate coord = selectedValue.getCoordinate();
        UTMCoordinate utm = coord.toUTM();
        latitudeField.setText(coord.getLatitude().toString());
        longitudeField.setText(coord.getLongitude().toString());
        altElipField.setText(String.format("%.3f", coord.getEllipsoidalHeight()));
        coordEsteField.setText(String.format("%.3f", utm.getEast()));
        coordNorteField.setText(String.format("%.3f", utm.getNorth()));
        meridianoCentralField.setText(coord.getLongitude().getCentralMeridian().toMeridianCentralString());
        cidadeUfField.setText(selectedValue.getCidade() + " / " + selectedValue.getUf());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        basesRbmcList = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        latitudeField = new javax.swing.JTextField();
        longitudeField = new javax.swing.JTextField();
        altElipField = new javax.swing.JTextField();
        coordEsteField = new javax.swing.JTextField();
        coordNorteField = new javax.swing.JTextField();
        meridianoCentralField = new javax.swing.JTextField();
        descritivoButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cidadeUfField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jScrollPane1.setViewportView(basesRbmcList);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Latitude");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Longitude");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Alt. Elip.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("UTM Este");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("UTM Norte");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Meridiano Central");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel6, gridBagConstraints);

        latitudeField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 223;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 2);
        jPanel1.add(latitudeField, gridBagConstraints);

        longitudeField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 223;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 2);
        jPanel1.add(longitudeField, gridBagConstraints);

        altElipField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 223;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 2);
        jPanel1.add(altElipField, gridBagConstraints);

        coordEsteField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 223;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 2);
        jPanel1.add(coordEsteField, gridBagConstraints);

        coordNorteField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 223;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 2);
        jPanel1.add(coordNorteField, gridBagConstraints);

        meridianoCentralField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 223;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 2);
        jPanel1.add(meridianoCentralField, gridBagConstraints);

        descritivoButton.setText("Baixar descritivo da web");
        descritivoButton.setEnabled(false);
        descritivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descritivoButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 4, 10, 4);
        jPanel1.add(descritivoButton, gridBagConstraints);

        jLabel7.setText("Cidade / UF");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel1.add(jLabel7, gridBagConstraints);

        cidadeUfField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 2);
        jPanel1.add(cidadeUfField, gridBagConstraints);

        jButton1.setText("Atualizar lista de Bases RBMC do IBGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 4, 10, 4);
        jPanel1.add(jButton1, gridBagConstraints);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void descritivoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descritivoButtonActionPerformed
        Desktop desktop = Desktop.getDesktop();
        try {
            BaseRBMC selectedValue = (BaseRBMC) basesRbmcList.getSelectedValue();
            if (selectedValue != null) {
                desktop.browse(new URI("ftp://geoftp.ibge.gov.br/RBMC/relatorio/Descritivo_" + selectedValue.getName() + ".pdf"));
            }
        } catch (Exception ex) {
            Logger.getLogger(RBMCPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(Main.getInstance(), "Não foi possível baixar o descritivo da web.");
        }
    }//GEN-LAST:event_descritivoButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            URL url = new URL("http://www.paulocanedo.com.br/geomapa/bases_rbmc.zip");
            File file = new File(OptionsPanel.getRBMCDir(), "bases_rbmc.zip");
            PC9Downloader.downloadWithSameThread(url, file);
            
            MiscUtils.extractZipFile(file, OptionsPanel.getRBMCDir());
            
            List<BaseRBMC> list = UtilRBMC.listAllRbmc();
            basesRbmcList.setModel(new DefaultComboBoxModel(list.toArray(new BaseRBMC[0])));
            basesRbmcList.clearSelection();
            JOptionPane.showMessageDialog(Main.getInstance(), "Dados de RBMC baixados com sucesso!");
        } catch (MalformedURLException ex) {
            Logger.getLogger(RBMCPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(RBMCPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altElipField;
    private javax.swing.JList basesRbmcList;
    private javax.swing.JTextField cidadeUfField;
    private javax.swing.JTextField coordEsteField;
    private javax.swing.JTextField coordNorteField;
    private javax.swing.JButton descritivoButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField latitudeField;
    private javax.swing.JTextField longitudeField;
    private javax.swing.JTextField meridianoCentralField;
    // End of variables declaration//GEN-END:variables
}
